var specData = [{name: "Alan Shearer", goals: 260},
                {name: "Andrew Cole", goals: 187},
                {name: "Wayne Rooney", goals: 175},
                {name: "Thierry Henry", goals: 175},
                {name: "Frank Lampard", goals: 172},
                {name: "Robbie Fowler", goals: 162},
                {name: "Michael Owen", goals: 150},
                {name: "Les Ferdinand", goals: 149},
                {name: "Teddy Sheringham", goals: 147},
                {name: "Robin Van Persie", goals: 135},
                {name: "Jimmy F Hasselbaink", goals: 128},
                {name: "Robbie Keane", goals: 126},
                {name: "Nicolas Anelka", goals: 125},
                {name: "Jermain Defoe", goals: 124},
                {name: "Dwight Yorke", goals: 123},
                {name: "Ian Wright", goals: 113},
                {name: "Steven Gerrard", goals: 112},
                {name: "Emile Heskey", goals: 111},
                {name: "Dion Dublin", goals: 111},
                {name: "Ryan Giggs", goals: 109},
                {name: "Paul Scholes", goals: 107},
                {name: "Darren Bent", goals: 106},
                {name: "Matthew Le Tissier", goals: 101},
                {name: "Didier Drogba", goals: 100},
                {name: "Emmanuel Adebayor", goals: 95},
                {name: "Yakubu", goals: 95},
                {name: "Ruud van Nistelrooy", goals: 95},
                {name: "Dimitar Berbatov", goals: 94},
                {name: "Kevin Phillips", goals: 92},
                {name: "Mark Viduka", goals: 92},
                {name: "Ole Gunnar Solskjaer", goals: 91},
                {name: "James Beattie", goals: 90},
                {name: "Kevin Davies", goals: 88},
                {name: "Dennis Bergkamp", goals: 87},
                {name: "Peter Crouch", goals: 86},
                {name: "Fernando Torres", goals: 85},
                {name: "Louis Saha", goals: 85},
                {name: "Carlos Tevez", goals: 84},
                {name: "Cristiano Ronaldo", goals: 84}];